export const ROOT_PATH = '/'
export const SIGN_IN_PATH = '/sign-in'
export const SIGN_UP_PATH = '/sign-up'
export const GUITAR_PATH = '/guitars/:id'
export const ADD_GUITAR_PATH = '/editor/add-new-guitar'
export const EDIT_GUITAR_PATH = '/editor/edit-guitar/:id'