name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          cd guitar_gems
          npm install
          
      - name: Start the development server
        run: npm run dev
        working-directory: guitar_gems

      - name: Wait for the server to be ready
        run: npx wait-on http://localhost:5173 --timeout=60000
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: guitar_gems
